---

- name: Update apt cache
  shell: apt update -y

- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
       - nginx

- name: Register nginx with the UFW Firewall
  shell: ufw allow 'Nginx HTTP'

- name: Configure Default Webpage
  shell: echo "Hello world" > /var/www/html/index.html

- name: Nginx service state
  service: name=nginx state=started enabled=yes
