---
# This role installs HAProxy and configures it.

- name: Update apt cache
  shell: apt update -y

- name: Download and install haproxy
  apt: name={{item}} state=present
  with_items:
       - haproxy

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
